# Generated by Django 5.2 on 2025-05-13 23:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('type', models.CharField(choices=[('I', 'Intensif'), ('S', 'Semi-Intensif')], max_length=1)),
                ('niveau', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('heures_par_semaine', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('duree_semaines', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'ordering': ['type', 'niveau'],
                'indexes': [models.Index(fields=['niveau'], name='cours_cours_niveau_0a1a59_idx'), models.Index(fields=['type'], name='cours_cours_type_a5c441_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('prenom', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom'], name='cours_ensei_nom_3119af_idx'), models.Index(fields=['prenom'], name='cours_ensei_prenom_1ffba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('periode_journee', models.CharField(choices=[('M', 'Matin'), ('S', 'Soir')], max_length=1)),
                ('capacite_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('O', 'Ouverte'), ('F', 'Fermée')], default='O', max_length=1)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cours.cours')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cours.enseignant')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('A', 'Actif'), ('I', 'Inactif')], default='A', max_length=1)),
                ('preinscription', models.BooleanField(default=False)),
                ('but', models.TextField(blank=True, null=True)),
                ('frais_inscription', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('motif_sortie', models.CharField(blank=True, max_length=100, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eleves.eleve')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours.session')),
            ],
            options={
                'ordering': ['date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='CoursPrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cours_prive', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('lieu', models.CharField(choices=[('E', 'École'), ('D', 'À domicile')], max_length=1)),
                ('eleves', models.ManyToManyField(related_name='cours_prives', to='eleves.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_prives', to='cours.enseignant')),
            ],
            options={
                'ordering': ['date_cours_prive', 'heure_debut'],
                'indexes': [models.Index(fields=['enseignant', 'date_cours_prive'], name='cours_cours_enseign_9ef0cc_idx'), models.Index(fields=['date_cours_prive'], name='cours_cours_date_co_ebf148_idx'), models.Index(fields=['heure_debut', 'heure_fin'], name='cours_cours_heure_d_90fdd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent')], max_length=1)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='cours.inscription')),
            ],
            options={
                'unique_together': {('inscription', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['statut'], name='cours_sessi_statut_382bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['statut'], name='cours_inscr_statut_0b1a5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('eleve', 'session')},
        ),
    ]
