version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # <<< PERSISTE LES DONNÉES

  web:
    build: ./backend
    command: gunicorn backend_ecole_peg.wsgi:application --bind 0.0.0.0:8000
    # pas de bind mount en prod (on exécute le code baked dans l'image)
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
    # commande par défaut de ton Dockerfile (souvent `npm start` / `next start`)
    ports:
      - "3001:3000"
    depends_on:
      - web

volumes:
  postgres_data:
