# Generated by Django 5.2 on 2025-05-13 23:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('cours_prive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='cours.coursprive')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='eleves.eleve')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='cours.inscription')),
            ],
            options={
                'ordering': ['date_emission'],
            },
        ),
        migrations.CreateModel(
            name='DetailFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_debut_periode', models.DateField(blank=True, null=True)),
                ('date_fin_periode', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='factures.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('mode_paiement', models.CharField(choices=[('PER', 'Personnel'), ('BPA', 'Bon de formation'), ('CAF', 'Chèque de formation'), ('HOS', 'Hospices général'), ('AUT', 'Autre')], max_length=3)),
                ('methode_paiement', models.CharField(choices=[('ESP', 'Espèce'), ('CAR', 'Carte bancaire'), ('VIR', 'Virement'), ('TWI', 'Twint'), ('TEL', 'Téléphone'), ('PAY', 'PayPal'), ('AUT', 'Autre')], max_length=3)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='factures.facture')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
